# This isn't a reusable workflow but a CI action for this repo itself - testing the contained workflows & scripts.
name: Script Tests

on:
  push:

jobs:
  updater:
    name: Updater @ ${{ matrix.host }}
    runs-on: ${{ matrix.host }}-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          - ubuntu
          - macos
          - windows
    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - run: Invoke-Pester
        working-directory: updater
        shell: pwsh
